library(GEOquery)
# directory = "path_to_GSEMatrix_file"
gsm <- getGEO(filename=directory, GSEMatrix=TRUE)
gse_expression_matrix <- exprs(gsm)
show(gsm)
dim(gse_expression_matrix)
colnames(gse_expression_matrix)
length(rownames(gse_expression_matrix))
dim(pData(gsm))
rownames(pData(gsm))
colnames(pData(gsm))
sample_title <- as.list(levels(pData(gsm)[[1,1]]))
sample_id <- as.list(levels(pData(gsm)[[1,2]]))
sample_description <- as.list(levels(pData(gsm)[[1,20]]))
sample_descriptor_vector <- unlist(sample_description)
sample_metadata <- read.table(text = sample_descriptor_vector, sep = " ", colClasses = "character")
colnames(sample_metadata) <- c("sample_no","animal_id","sex","age","diet")
sample_metadata$geo_accession <- unlist(sample_id) 
sample_title_vector <- unlist(sample_title)
sample_title_df <- read.table(text = sample_title_vector, sep = ",", colClasses = "character")
colnames(sample_title_df) <- c("tissue","array_id","sample_title")
phenoData <- cbind(sample_title_df, sample_metadata)
age_days <- as.integer(phenoData$age)
age_weeks <- age_days/7
age_months <- age_weeks/4
phenoData$age_months <- age_months
males_adlib <- subset(phenoData,sex=="M" & diet=="A", select=c(1:10))
males_adlib_sample_no <- as.integer(males_adlib$sample_no)
females_adlib <- subset(phenoData,sex=="F" & diet=="A", select=c(1:10))
females_adlib_sample_no <- as.integer(females_adlib$sample_no)
adlib_group <- subset(phenoData, diet=="A", select=c(1:10))
adlib_sample_no <- as.integer(adlib_group$sample_no)
males_cr <- subset(phenoData,sex=="M" & diet=="C", select=c(1:10))
males_cr_sample_no <- as.integer(males_cr$sample_no)
females_cr <- subset(phenoData,sex=="F" & diet=="C", select=c(1:10))
females_cr_sample_no <- as.integer(females_cr$sample_no)
cr_group <- subset(phenoData, diet=="A", select=c(1:10))
cr_group_sample_no <- as.integer(cr_group$sample_no)